## Assignment 2
* Due: Tuesday 2/25/2020 by  9 PM 
* Topics: pandas and numpy

## Instructions
* Download your notebook as a PDF
* Turn in both the notebook and PDF
* Show the output of your code working on the sample data, like below.  
* If techniques are specified, use them.  Otherwise, feel free to solve the problem how you want.  
* Try to keep your code clean, concise and avoid loops if necessary.  
* You have to show your work (code).
* You will be graded:
    * The functionality of your code (Does it do what it was meant to)
    * Showing the output on the sample data provided
    * How concise it is (did you use a for loop when you could have used a comprehension for instance).  Simply put, try and write clean, concise and readable code (don't use 10 lines for what could have been done in 4).
    * Even if the answer isn't perfect, make an honest attempt as partial credit will be given.

## Question 1
* sklearn has the iris dataset built in
* this is what we will be working with
* put the iris data into a dataframe where we have 5 columns (the 4 features and the target)
* but the target shouldn't be numerical, it should be the actual label (so put setosa not 0 in the target column) 

In [2]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

iris = load_iris()

In [21]:
feature_names = iris.feature_names
features = pd.DataFrame(iris.data, columns = feature_names)
target = pd.DataFrame(iris.target, columns = ['target'])

In [22]:
pd.concat([features, target],  axis = 1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [19]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [79]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [81]:
new_list = []
for i in iris.target:
    if i == 0:
        new_list.append(iris.target_names[0])
    elif i == 1:
        new_list.append(iris.target_names[1])
    elif i == 2:
        new_list.append(iris.target_names[2])

In [82]:
new_list

['setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',


## Question 2
* using the data array from the iris variable (should be a numpy array of size 150x4), for each row and column, find the sum, min and max
* print out the results, but for the rows, show only the first 5 elements of the array and display the length (otherwise it will be large arrays since each row has a value)

In [74]:
#first 5 rows rows
list(map(lambda x: (x.sum(), x.min(), x.max()), iris.data[0:5]))

[(10.2, 0.2, 5.1),
 (9.5, 0.2, 4.9),
 (9.4, 0.2, 4.7),
 (9.399999999999999, 0.2, 4.6),
 (10.2, 0.2, 5.0)]

In [92]:
#alternate first 5 rows
[(j.sum(axis = 0), min(j), max(j)) for j in iris.data[0:5]]

[(10.2, 0.2, 5.1),
 (9.5, 0.2, 4.9),
 (9.4, 0.2, 4.7),
 (9.399999999999999, 0.2, 4.6),
 (10.2, 0.2, 5.0)]

In [101]:
#rows
print(iris.data.sum(axis = 1)[0:5], iris.data.min(axis = 1)[0:5], iris.data.max(axis = 1)[0:5], iris.data.shape[0])

[10.2  9.5  9.4  9.4 10.2] [0.2 0.2 0.2 0.2 0.2] [5.1 4.9 4.7 4.6 5. ] 150


In [102]:
#columns
print(iris.data.sum(axis = 0)[0:5], iris.data.min(axis = 0)[0:5], iris.data.max(axis = 0)[0:5])

[876.5 458.6 563.7 179.9] [4.3 2.  1.  0.1] [7.9 4.4 6.9 2.5]


In [71]:
#iris.data.T

## Question 3
* write a function to return the multiplication of two matrices
* use some sort of error handling to make sure the dimensions are compatible
* use the function to multiply the iris data (don't use the label column) by it's transpose
* what are the dimensions of the result
* put the sum of each row of the resulting matrix into a vector, printing out the length and first 5 elements.
* put the sum of each column of the resulting matrix in a vector and print it out.

In [65]:
def matrix_multiply(a, b):
    assert a.shape[1] == b.shape[0], 'dimensions of matrix do not allow for multiplication'
    
    result = a@b    
    return result

In [66]:
iris.data.shape, iris.data.T.shape

((150, 4), (4, 150))

In [68]:
newmatrix = matrix_multiply(iris.data, iris.data.T)
newmatrix.shape

(150, 150)

In [83]:
newmatrix = matrix_multiply(iris.data, iris.data.T)
newmatrix

array([[40.26, 37.49, 37.03, ..., 51.33, 51.54, 48.09],
       [37.49, 35.01, 34.49, ..., 48.53, 48.6 , 45.41],
       [37.03, 34.49, 34.06, ..., 47.31, 47.5 , 44.32],
       ...,
       [51.33, 48.53, 47.31, ..., 82.29, 83.18, 77.47],
       [51.54, 48.6 , 47.5 , ..., 83.18, 84.45, 78.46],
       [48.09, 45.41, 44.32, ..., 77.47, 78.46, 73.06]])

In [87]:
row_vector = list(map(lambda x: x.sum(), newmatrix))
print('The length of the vector is: {}. The first 5 elements are: {}'.format(len(row_vector), row_vector[0:5]))

The length of the vector is: 150. The first 5 elements are: [6900.41, 6495.810000000001, 6355.860000000001, 6335.089999999998, 6858.620000000001]


In [84]:
col_vector = [k.sum() for k in newmatrix[:].T]
print(col_vector)

[6900.41, 6495.810000000001, 6355.860000000001, 6335.089999999998, 6858.620000000001, 7551.89, 6434.289999999999, 6823.27, 6011.700000000001, 6580.05, 7311.450000000001, 6704.34, 6390.17, 5782.810000000001, 7630.5199999999995, 7931.400000000001, 7326.41, 6918.4, 7750.99, 7112.349999999999, 7286.61, 7084.479999999998, 6282.54, 7031.769999999999, 6873.449999999999, 6696.200000000001, 6915.620000000001, 7044.429999999999, 6942.200000000001, 6524.969999999999, 6566.759999999998, 7209.85, 7301.6, 7572.03, 6598.04, 6562.4400000000005, 7194.64, 6752.980000000001, 6001.19, 6910.92, 6774.380000000001, 5785.81, 6092.91, 6997.459999999999, 7355.82, 6426.150000000001, 7150.73, 6324.58, 7223.8, 6721.04, 10504.27, 9883.62, 10501.490000000002, 8364.199999999999, 9844.199999999999, 9050.649999999998, 9972.56, 7435.6, 9941.73, 8246.309999999998, 7452.549999999999, 9184.539999999999, 8702.619999999999, 9577.84, 8501.529999999999, 10026.35, 9090.699999999999, 8812.99, 9249.72, 8451.22, 9668.45, 9119.3999

## Question 4
* create a subset of the iris dataframe that doesn't have the label column
* for each row, find the index of the min and max feature value
    * if we have a row with values [10,2,3,4] we want to return 1 for min and 0 for max, as these are the indicies that align to the min and max values
* the result should be two arrays of length 150 (one for each row) with the indices of the min and max value

## Question 5
* Use the above two arrays to make a dataframe with 2 columns, the first being the feature of minimum value and the second the feature name of the maximum value
* note, don't have the cell values be the index value of the min/max value, have it be the feature name
    * a row should be [min_val = sepal width (cm), max_val = petal length (cm)]
* show the distributions for max and min features (how many times is each feature the max and min value for a row)

## Question 6
* Describe a situation the functionality from question 4 and 5 could be of use?

## Question 7
* sort the feature values for each row and replace the indices with the feature names
    * so each row will have 4 columns, the first column being the feature name that is the highest value, the second column being the feature name that is the second highest value, etc.
* note, watch out how argsort in numpy works.  you will need to reverse the order somehow.  the sorted(reverse = True) functionality might be of help.
* make sure to replace the index values with the feature name, as we did above
* put the resulting 2-d array into a pandas dataframe and print the first 5 rows.
* hint, look at the apply_along_axis() method for numpy arrays

## Question 8
* apply z-score normalization to each column in the iris data (note you do not need the target/label column)
* column wise meaning, treat each column as an array, and find the standard deviations and means of that column
* note, you can use zscore from scipy.stats
* results should be a pandas dataframe, printing out 5 rows and running the describe() method on the dataframe

## Question 9
* make a function that takes in a 2d numpy array X, a 1d numpy array Y and the size the training data, test data and valiation datasets.  
* return 6 items
    * train_x, train_y, test_x, test_y, val_x, val_y
* do not use any modules.  this can be solved using bracket notation to subset.  Note // will take care of decimals in doing division. you could also use int() to convert the float to a whole number
* make the params for the training, test and val size be decimals, that repsent percentages of the data.  For instance .8, .1, .1 means an 80% training, 10% test and 10% validation split
* use an assert to make sure the numbers add to 1
* print out the dimensions of all 6 elements, using iris as a test case with an 80-10-10 split

## Question 10
* using pandas, find the sum of each feature by species type (label)
* do the same, but find the min, max and median as well

## Question 11
* mean center each column of the iris dataframe (excluding the label column of course)
* this means, for each column, the mean should be zero.  to accomplish this we can subtract the column mean from each element of the column
* note, broadcasting, which if we have say a 150 row and 4 column dataframe, can  take a row vector of size 4 and apply it to each element
*  thus, we can answer this questions doing something like df - df_col_means
* run the describe() method at the end to show the data has been mean center

## Quesiton 12
* Explain what the axis mean in regards to a pandas dataframe and numpy array
* How would you groupby two columns in pandas?
* What functions are used to read in csvs and excel files in pandas

## Question 13
* using Pandas, subset the dataset for only species setosa and petal length > 1.3
* sum the feature columns and display the results for each (excluding the label column)
* do the same, but change the and to an or, and repeat the same calculation

## Question 14
* write a lambda that subtracts 2 from all elements of a pandas dataframe
* display the top 5 rows
* use the same lambda,  but applying it to the sepal length  column only
* so the output should be the top 5 rows of a dataframe where all cells have had 2 subtracted and then another dataframe where only sepal length has 2 subtracted from it

## Question 15
* normalize each column of pandas dataframe to 0-1 scale.
* hint
    * 0-1 is done by using (X - xmin)/(xmax - xmin)
    * the approach should be similar to when we meean centered the dataframe

## Question 16
* assume the below 2 matrices, the first is observations and the second is cluster centers
* using cdist from scipy, create a matrix where the rows represent our 3 observations and the columns represent our 2 clusters and the cells values are the euclidean distances between a given observation and cluster
* when would this be of use?  

In [18]:
observations = np.array([
    [1,2,3],
    [4,3,1],
    [2,3,4]
])

cluster_centers = np.array([
    [2,3,1],
    [2,1,3]
])